### ISSUE TITLE
Use builtin File functions and get rid of the module

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/advdupe2#105]
Garry's Mod provides all of the functions (and even more) which were added in the binary module to make saving faster on Windows OS.

- [ ] Use builtin File functions
- [ ] Remove binary module

**Comment by bigdogmat** [comment]
They're already being used

**Comment by thegrb93** [comment]
It is performance related. Try timing with and without and see.

**Comment by oldmud0** [comment]
and Linux? and Mac?

**Comment by TBbadmofo** [comment]
https://facepunch.com/showthread.php?t=1219442&highlight=
Here is the thread reporting the slow file stream issues on Windows with GLua. It didn't seem to be an issue on Linux or Mac. I created the module so that users running on windows would not experience extreme lag when saving. It already falls back on the GMod file functions if the module is not installed.

**Comment by thegrb93** [comment]
https://github.com/wiremod/advdupe2/pull/138/files fixes this
