### ISSUE TITLE
attempt to index field 'context' (a nil value)

### ISSUE THREAD

**Issue by Jack37** [wiremod/advdupe2#21]
```
[AdvDupe2Notify]    Pasting...
[AdvDupe2Notify]    addons/wire/lua/entities/gmod_wire_expression2/init.lua:109: attempt to index field 'context' (a nil value)
[AdvDupe2Notify]    Finished Pasting!
```
1. Spawn two props and weld them together
2. Place E2 on one of the props
3. Change sbox_maxprops to 3

Now if you dupe the prop with the E2 on it, you will get the error after pasting, which also results in removing both props (whole contraption when there are many props). If you dupe the second prop without E2, it will spawn fine.

Basically this is happening if you hit the prop limit while pasting and the contraption has E2 in it.

**Comment by Squishyy** [comment]
This error is still occurring, however the situation I've encountered is not caused by sbox_maxprops as far as I'm aware, and it happens when pasting one of my own duplications (can upload the dupe if necessary). Also, this didn't used to be a problem, I'd say the dupe was working at least 6 months ago, for what that's worth. Any ideas at all on what's causing this or how to get around it? I personally don't know enough about modding gmod to figure this out, I would appreciate any help with this very much.

Another small difference, using the current master the error is on a different line:

`addons/wire/lua/entities/gmod_wire_expression2/init.lua:120: attempt to index field 'context' (a nil value)
`

Although I assume that's merely due to code being added above it since this issue was originally posted as the current workshop version references line 109 as well.

**Comment by thegrb93** [comment]
Seems fixed. Also not a advdupe2 issue.
