### ISSUE TITLE
Make numbering when saving file with same name prepend 0s

### ISSUE THREAD

**Issue by TheLightBringer1991** [wiremod/advdupe2#227]
There's a problem when naming dupes with numbers. The names get auto sorted but, for example, 4 is put after 15. It's like the sorting system doesn't understand the existance of numbers bigger than 10, so it reads the first number only, so even 300 is put before 4.

**Comment by thegrb93** [comment]
Yah its not a bug. Linux does it too. Prepend your numbers with 0 to prevent. 001, 002, 003, 004

**Comment by thegrb93** [comment]
I think the autonamer needs to be updated though.

**Comment by TheLightBringer1991** [comment]
It doesn't work either by adding 0s in front of it. 04 will be put after 015 anyway. That's a bug, and if it's not a bug, that's coded badly.

**Comment by Divran** [comment]
You mean when files are displayed in a file explorer? As was already mentioned, the fix is to prepend with zeros. `04` vs `15`, or `004` vs `015`. The trick is to have the same number of digits.

I'm reasonably sure windows used to do this as well, in older versions such as windows XP and windows 7, but I just tested it and windows 10 seems to properly check if the first few characters are numbers, and sorts the files accordingly.

**Comment by thegrb93** [comment]
Forgot to reopen

**Comment by thegrb93** [comment]
Yeah windows smartly recognizes numbering. I've yet to use a linux file manager as fast and smart as windows explorer.
