### ISSUE TITLE
Already Opening File

### ISSUE THREAD

**Issue by rocthort** [wiremod/advdupe2#29]
Whenever I try to open a dupe, it spits out a lua error. Sometimes (rarely) it will work but its refusing to work.

```
[ERROR] addons/advdupe2/lua/advdupe2/cl_networking.lua:189: attempt to index a nil value
  1. LoadGhosts - addons/advdupe2/lua/advdupe2/cl_networking.lua:189
   2. callback - addons/advdupe2/lua/advdupe2/cl_networking.lua:243
    3. Decode - addons/advdupe2/lua/advdupe2/sh_codec.lua:483
     4. InitializeUpload - addons/advdupe2/lua/advdupe2/cl_networking.lua:241
      5. DoNodeLeftClick - addons/advdupe2/lua/advdupe2/file_browser.lua:174
       6. unknown - addons/advdupe2/lua/advdupe2/file_browser.lua:993
```

**Comment by AbigailBuccaneer** [comment]
Can you link to this Facepunch thread? As far as I'm aware, AdvDupe2 hasn't had any files 'released' on Facepunch since it was moved to the Wire Team's control.

**Comment by l-Rocky-l** [comment]
This is the same error I am having :(


[ERROR] addons/advdupe2-master/lua/advdupe2/sh_codec.lua:446: attempt to index local 'encodedDupe' (a nil value)
  1. Decode - addons/advdupe2-master/lua/advdupe2/sh_codec.lua:446
   2. InitializeUpload - addons/advdupe2-master/lua/advdupe2/cl_networking.lua:242
    3. DoNodeLeftClick - addons/advdupe2-master/lua/advdupe2/file_browser.lua:174
     4. unknown - addons/advdupe2-master/lua/advdupe2/file_browser.lua:993

**Comment by l-Rocky-l** [comment]
When you open a file it says already opening file!

**Comment by AbigailBuccaneer** [comment]
@l-Rocky-l are you sure you have the latest version? Those line numbers don't seem to make sense. [lua/advdupe2/sh_codec.lua:446](https://github.com/wiremod/advdupe2/blob/1d77d8c0fdb8a24bc0bd12876e0ad14291d75136/lua/advdupe2/sh_codec.lua#L446) is fine, but [lua/advdupe2/cl_networking.lua:242](https://github.com/wiremod/advdupe2/blob/1d77d8c0fdb8a24bc0bd12876e0ad14291d75136/lua/advdupe2/cl_networking.lua#L242) is a comment.

Assuming the first line of that stack trace is correct, then the second one is probably supposed to be [lua/advdupe2/cl_networking.lua:230](https://github.com/wiremod/advdupe2/blob/1d77d8c0fdb8a24bc0bd12876e0ad14291d75136/lua/advdupe2/cl_networking.lua#L230). The cause of this error, then, would be that `file.Exists(ReadPath, "DATA")` returns `true`, but `file.Read(ReadPath)` returns `nil`. So this may be caused by file permissions or something similar. Should be fairly easy to fix by just ensuring that `read ~= nil`.

**Comment by AbigailBuccaneer** [comment]
(I hope none of you saw that previous comment of mine I've deleted - it had some incorrect info caused by me not being good at GitHub :stuck_out_tongue_winking_eye: )

@l-Rocky-l that error isn't the same as @rocthort's - it looks to have been another instance of #25. I've just fixed that particular case in fb2f76826525be19d133637cc39cddceaa7572ea. When you try and do whatever you did, you should now get an error saying "File could not be read" rather than it trying to decode it anyway.

**Comment by AbigailBuccaneer** [comment]
Given the line numbers in the stack trace, @rocthort isn't using the latest `master` version of AdvDupe2: they're consistent with 57072b43301f39196f2393e220f294ebef4e220f. [lua/advdupe2/cl_networking.lua:189](https://github.com/wiremod/advdupe2/blob/57072b43301f39196f2393e220f294ebef4e220f/lua/advdupe2/cl_networking.lua#L189) then does have a reason for erroring when 187 and 188 would.

**Comment by AbigailBuccaneer** [comment]
I suspect the best way to fix this once and for all is liberal use of `pcall`/`xpcall` - if it can't create a ghost it should maybe emit a warning and continue, whereas if `AdvDupe2.Decode` fails then that should be caught and handled (setting `uploading = false` so it doesn't give "already opening file" errors).

**Comment by l-Rocky-l** [comment]
One of my friends looked at the error and apparently fixed it so, I dont know if that will help you figuring this error out?

**Comment by AbigailBuccaneer** [comment]
We're happy to receive pull requests and patches. (Note that I've already fixed the error you were having, @l-Rocky-l, and it's not the same as the one @rocthort was.)

**Comment by l-Rocky-l** [comment]
I had the latest version, after this error I immietly thought to reinstall the addon from the legit page, right here.

**Comment by l-Rocky-l** [comment]
And its weird if you had already fixed it and it is yet happening to me.

**Comment by AbigailBuccaneer** [comment]
@l-Rocky-l, I fixed it after you reported it - you'll have to get the latest again and test it again.
