### ISSUE TITLE
duplicator.Allow does not work if Spawnable is false and entity isn't registered

### ISSUE THREAD

**Issue by Rusketh** [wiremod/advdupe2#351]
Please change line 899
https://github.com/wiremod/advdupe2/blob/master/lua/advdupe2/sv_clipboard.lua#L899

So that the allowed list can be used to override the other 2 checks. Some SENT's are set to none spannable because they are tool spawned. Currently, any entity spawned by a tool is not dupable, this is causing issues on my server as we have a lot of custom sents spawned by tools that we need to dupe.

**Comment by thegrb93** [comment]
Your entity spawned by tool should be registered for duplication or allowed for generic duplication. IsAllowed is only called for generic duplication.

**Comment by thegrb93** [comment]
This check is the only thing preventing spawning whatever random hl2 entity the player wants.

**Comment by thegrb93** [comment]
https://wiki.facepunch.com/gmod/duplicator.RegisterEntityClass
this calls Allow internally

or you can do it manually https://wiki.facepunch.com/gmod/duplicator.Allow

**Comment by thegrb93** [comment]
Ah, I just realized your problem.

Ents with Spawnable set to false should still pass because of the 'EntityClass' check.

**Comment by thegrb93** [comment]
I guess unless it's allowed and not registered. I think we can change it then.

**Comment by thegrb93** [comment]
Gmod's duplicator does this check https://github.com/Facepunch/garrysmod/blob/0ec74aab0858807677180bfde8bb0e109c3544cf/garrysmod/lua/includes/modules/duplicator.lua#L421 . I think the reason is because all SENTs are allowed and many don't DisableDuplicator so I think the best solution is registering your entity with duplicator if spawnable is false.
