### ISSUE TITLE
Opening another file while pasting causes bugged 'Already opening file' error

### ISSUE THREAD

**Issue by thegrb93** [wiremod/advdupe2#9]
Opening another file while pasting causes 'Already opening file' error which won't go away until a map restart.

I think the steps that happened were,
1. Open a file and paste
2. Before the file is finished pasting, open another file. (This file will begin ghosting)
3. Click to attempt pasting. "Adv duplicator is busy"
4. The previous file finished pasting.
5. Click to try pasting my second file, but it begins pasting the first file again.
6. Push z before the pasting finishes.
7. Try reopening the 2nd file. "Already opening file"

**Comment by Jack37** [comment]
This could be easily fixed by setting ````uploading = false```` once the upload has been aborted here https://github.com/wiremod/advdupe2/blob/master/lua/advdupe2/cl_networking.lua#L294 but then there's a problem with the toolscreen saying "Opening:" and ghosting of the newly opened file, since these happen before we check if the file can be actually opened (https://github.com/wiremod/advdupe2/blob/master/lua/advdupe2/cl_networking.lua#L251). Can we check if the duplicator is pasting before the decoding begins?

**Comment by thegrb93** [comment]
Fixed by https://github.com/wiremod/advdupe2/pull/66
