### ISSUE TITLE
Wire clutches not pasting correctly

### ISSUE THREAD

**Issue by CheezusChrust** [wiremod/advdupe2#94]
After I link a couple of entities with a wire clutch and then duplicate the entities, after I spawn them again, the clutch is unlinked from some of the entities. If I had to take a wild guess, it's assigning the linked entities to the clutch as soon as the clutch controller itself gets pasted in, and if one or two of the entities doesn't exist yet (contraption isn't pasted fully) it simply refuses to link them. I could be wrong as I don't have any experience on how adv dupe 2 works, but this issue bugs me because I have to re link random wheels when I paste my car which makes use of wire clutches for diff locks.

**Comment by AbigailBuccaneer** [comment]
Entities that need to be linked to others use a system of `BuildDupeInfo`/`ApplyDupeInfo`, that's standardised across advduplicator and advdupe2: before duping, entities will have [`ENT:BuildDupeInfo`](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_clutch.lua#L241) called if it exists. This builds a table which contains entity IDs of linked entities. Once every entity has been duplicated, [`ENT:ApplyDupeInfo`](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_clutch.lua#L254) will be called on each entity, and it's passed the table that was created by `ApplyDupeInfo` as well as a function which maps original entity IDs to the new entities, for them to link up to. `gmod_wire_clutch` looks like it handles this alright, so the cause is likely not your wild guess. :wink:

**Comment by CheezusChrust** [comment]
Ah alright, I tried. Hopefully someone can figure this out as although it's not a HUGE problem since I can always just re-link them after it spawns, it mildly annoys me and a few others who are experiencing the same issue.

**Comment by oldmud0** [comment]
Linkback: https://www.reddit.com/r/wiremod/comments/7fxv54/will_wiremod_clutches_ever_be_fixed_for_adv_dupe_2/

**Comment by thegrb93** [comment]
Found that its a wire clutch bug, ill put the fix in wire repo
